datastore:
  cls: lsst.daf.butler.datastores.posixDatastore.PosixDatastore
  root: default_butler_repository
  records:
    table: PosixDatastoreRecords
  create: true
  templates:
    default: "{collection}/{datasetType}/{tract:?}/{patch:?}/{abstract_filter:?}/{camera:?}/{physical_filter:?}/{visit:?}"
  formatters:
    TablePersistable: lsst.daf.butler.formatters.fitsCatalogFormatter.FitsCatalogFormatter
    TablePersistableWcs: lsst.daf.butler.formatters.fitsCatalogFormatter.FitsCatalogFormatter
    TablePersistablePsf: lsst.daf.butler.formatters.fitsCatalogFormatter.FitsCatalogFormatter
    TablePersistableCoaddInputs: lsst.daf.butler.formatters.fitsCatalogFormatter.FitsCatalogFormatter
    TablePersistableVisitInfo: lsst.daf.butler.formatters.fitsCatalogFormatter.FitsCatalogFormatter
    TablePersistableApCorr: lsst.daf.butler.formatters.fitsCatalogFormatter.FitsCatalogFormatter
    TablePersistableCalib: lsst.daf.butler.formatters.fitsCatalogFormatter.FitsCatalogFormatter
    TablePersistableTransmissionCurve: lsst.daf.butler.formatters.fitsCatalogFormatter.FitsCatalogFormatter
    ImageF: lsst.daf.butler.formatters.fitsCatalogFormatter.FitsCatalogFormatter
    MaskX: lsst.daf.butler.formatters.fitsCatalogFormatter.FitsCatalogFormatter
    SourceCatalog: lsst.daf.butler.formatters.fitsCatalogFormatter.FitsCatalogFormatter
    Exposure: lsst.daf.butler.formatters.fitsExposureFormatter.FitsExposureFormatter
    ExposureF: lsst.daf.butler.formatters.fitsExposureFormatter.FitsExposureFormatter
    ExposureI: lsst.daf.butler.formatters.fitsExposureFormatter.FitsExposureFormatter
    Catalog: lsst.daf.butler.formatters.fitsCatalogFormatter.FitsCatalogFormatter
    PeakCatalog: lsst.daf.butler.formatters.fitsCatalogFormatter.FitsCatalogFormatter
    SourceCatalog: lsst.daf.butler.formatters.fitsCatalogFormatter.FitsCatalogFormatter
    ImageF: lsst.daf.butler.formatters.fitsExposureFormatter.FitsExposureFormatter
    ImageU: lsst.daf.butler.formatters.fitsExposureFormatter.FitsExposureFormatter
    DecoratedImageU: lsst.daf.butler.formatters.fitsExposureFormatter.FitsExposureFormatter
    MaskX: lsst.daf.butler.formatters.fitsExposureFormatter.FitsExposureFormatter
    Exposure: lsst.daf.butler.formatters.fitsExposureFormatter.FitsExposureFormatter
    ExposureF: lsst.daf.butler.formatters.fitsExposureFormatter.FitsExposureFormatter
    ExposureI: lsst.daf.butler.formatters.fitsExposureFormatter.FitsExposureFormatter
    SkyMap: lsst.daf.butler.formatters.pickleFormatter.PickleFormatter
    Background: lsst.daf.butler.formatters.fitsCatalogFormatter.FitsCatalogFormatter
    Config: lsst.daf.butler.formatters.pexConfigFormatter.PexConfigFormatter
    Packages: lsst.daf.butler.formatters.pickleFormatter.PickleFormatter
    PropertyList: lsst.daf.butler.formatters.pickleFormatter.PickleFormatter
    PropertySet: lsst.daf.butler.formatters.pickleFormatter.PickleFormatter
