# Default with a sqlLite registry
registry:
  cls: lsst.daf.butler.registries.sqliteRegistry.SqliteRegistry
  db: 'sqlite:///:memory:'
  limited: false
  skypix:
    cls: lsst.sphgeom.HtmPixelization
    level: 7
