storageClasses:
  StructuredDataDict:
    pytype: dict
  StructuredDataList:
    pytype: list
  TablePersistable:
    pytype: lsst.afw.table.io.Persistable
  TablePersistableWcs:
    pytype: lsst.afw.geom.skyWcs.SkyWcs
  TablePersistablePsf:
    pytype: lsst.afw.detection.Psf
  TablePersistableCoaddInputs:
    pytype: lsst.afw.image.CoaddInputs
  TablePersistableVisitInfo:
    pytype: lsst.afw.image.VisitInfo
  TablePersistableApCorr:
    pytype: lsst.afw.image.ApCorrMap
  TablePersistableCalib:
    pytype: lsst.afw.image.Calib
  TablePersistableTransmissionCurve:
    pytype: lsst.afw.image.TransmissionCurve
  ImageF:
    pytype: lsst.afw.image.ImageF
  ImageU:
    pytype: lsst.afw.image.ImageU
  DecoratedImageU:
    pytype: lsst.afw.image.DecoratedImageU
  MaskX:
    pytype: lsst.afw.image.MaskX
  Catalog:
    pytype: lsst.afw.table.BaseCatalog
  PeakCatalog:
    pytype: lsst.afw.detection.PeakCatalog
  SourceCatalog:
    pytype: lsst.afw.table.SourceCatalog
  SkyMap:
    pytype: lsst.skymap.BaseSkyMap
  PropertyList:
    pytype: lsst.daf.base.PropertyList
  Exposure: &Exposure
    pytype: lsst.afw.image.Exposure
    assembler: lsst.daf.butler.assemblers.exposureAssembler.ExposureAssemblerMonolithic
    components:
      image: ImageF
      mask: MaskX
      variance: ImageF
      wcs: TablePersistableWcs
      psf: TablePersistablePsf
      calib: TablePersistableCalib
      visitInfo: TablePersistableVisitInfo
      apCorrMap: TablePersistableApCorr
      coaddInputs: TablePersistableCoaddInputs
      metadata: PropertyList
  ExposureF:
    <<: *Exposure
    pytype: lsst.afw.image.ExposureF
  ExposureI:
    <<: *Exposure
    pytype: lsst.afw.image.ExposureI
  ExposureComposite: &ExposureComposite
    <<: *Exposure
    assembler: lsst.daf.butler.assemblers.exposureAssembler.ExposureAssembler
  ExposureCompositeF:
    <<: *ExposureComposite
    pytype: lsst.afw.image.ExposureF
  ExposureI:
    <<: *ExposureComposite
    pytype: lsst.afw.image.ExposureI
  Background:
    pytype: lsst.afw.math.BackgroundList
  Config:
    pytype: lsst.pex.config.Config
  Packages:
    pytype: lsst.base.Packages
